name: angular_tour_of_heroes
description: Tour of Heroes
version: 0.0.1
# homepage: https://www.example.com
# author: Rafael Enriquez Herrador <rafael.enriquez.herrador@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_forms: ^2.0.0

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  test: ^1.5.1
